2015-12-24 17:59:34,898 - DEBUG - TianchengTest.py[179] - 测试开始时间: 2015-12-24 17:59:34
2015-12-24 17:59:34,901 - DEBUG - TianchengTest.py[26] - 运行模式：部分执行
2015-12-24 17:59:34,904 - DEBUG - TianchengTest.py[183] - 待执行用例: {'CCS': [4]}
2015-12-24 17:59:34,907 - DEBUG - TianchengTest.py[186] - Starting thread: TestRunThread
2015-12-24 17:59:34,911 - DEBUG - TianchengTest.py[145] - [TestRunThread] 开始执行用例: (CCS, 4)
---
2015-12-24 17:59:34,915 - ERROR - 'unicode' object has no attribute 'encoding'
Traceback (most recent call last):
  File "D:\AutoTest\Code\TianchengInterface_Testing\src\ModCCS.py", line 69, in parseParamsForDriver
    values[i] = EncryptLib.get_base64(jsonvalue.encoding('utf8'))
AttributeError: 'unicode' object has no attribute 'encoding'
2015-12-24 17:59:34,923 - ERROR - 'bool' object is not iterable
Traceback (most recent call last):
  File "D:\AutoTest\Code\TianchengInterface_Testing\src\Interface_DriverEngine.py", line 195, in RunTestCase
    RunResult = self.RunCCSCase(sheet, testid, TestData, TestEnvironment)
  File "D:\AutoTest\Code\TianchengInterface_Testing\src\Interface_DriverEngine.py", line 156, in RunCCSCase
    TestData, unique_id = ModCCSO.parseParamsForDriver(TestData)
TypeError: 'bool' object is not iterable
2015-12-24 17:59:34,936 - DEBUG - TianchengTest.py[149] - [TestRunThread] 测试操作不成功: (CCS, 4)
2015-12-24 17:59:35,911 - DEBUG - TianchengTest.py[193] - Starting thread: TestAssertThread
2015-12-24 17:59:35,917 - DEBUG - TianchengTest.py[200] - 等待子线程TestRunThread结束...
2015-12-24 17:59:35,940 - DEBUG - TianchengTest.py[202] - 子线程：TestRunThread结束
2015-12-24 17:59:35,944 - DEBUG - TianchengTest.py[204] - 等待子线程TestAssertThread结束...
2015-12-24 17:59:45,917 - DEBUG - TianchengTest.py[124] - [TestAssertThread] 从队列taskassert_queue中取任务超时
2015-12-24 17:59:45,930 - DEBUG - TianchengTest.py[206] - 子线程：TestAssertThread结束
2015-12-24 17:59:45,934 - DEBUG - TianchengTest.py[214] - 测试结束时间: 2015-12-24 17:59:45
2015-12-24 17:59:45,937 - DEBUG - TianchengTest.py[217] - testcase_result: {('CCS', 4): ('ERROR', u'\u6d4b\u8bd5\u64cd\u4f5c\u4e0d\u6210\u529f')}
2015-12-24 17:59:45,941 - DEBUG - GenerateReport.py[126] - 生成测试结果报告: .\result\Test_Report_Filename20151224175945.html
